### PR TITLE
Change defaut color to white not dark blue.

### PR DESCRIPTION
**Pull request by bickman**
Change the clock background color to white not dark blue in light mode.

### CODE REVIEW

**Comment by jesec** [comment]
Thank you for your contribution. But:
1. We don't use Github PRs. Please submit your change to [Gerrit](https://review.lineageos.org). Check [How to use Gerrit](https://wiki.lineageos.org/usinggerrit-howto.html) of our Wiki for more details. 
2. Dark blue is kept for light mode for a reason. Yes, from a design point of view, it makes sense to make the background white in light mode when we have a black background for dark theme. However, white is really bright and we don't want to make users blind when they check the clock in the midnight. During internal discussions about redesign, I am actually in favor of getting rid of light mode altogether but some other members still like the dark blue.

**Comment by BAProductions** [comment]
I’ve already done it on my ROM

**Comment by BAProductions** [comment]
[https://drive.google.com/file/d/1--w0HqZR6XqOv6VcQnS5tLBga_6VO113/view?usp=drivesdk
]()

**Comment by bickman** [comment]
> Thank you for your contribution. But:
> 
> 1. We don't use Github PRs. Please submit your change to [Gerrit](https://review.lineageos.org). Check [How to use Gerrit](https://wiki.lineageos.org/usinggerrit-howto.html) of our Wiki for more details.
> 2. Dark blue is kept for light mode for a reason. Yes, from a design point of view, it makes sense to make the background white in light mode when we have a black background for dark theme. However, white is really bright and we don't want to make users blind when they check the clock in the midnight. During internal discussions about redesign, I am actually in favor of getting rid of light mode altogether but some other members still like the dark blue.

Change background to #ffffff is not what I really mean, I mean light/dark grey or light/dark blue with less saturation, please don't use color with high saturation like #1A237E. I recommad to use like #DDDDDD , in light mode， #303030  in dark mode , if you want dark background in normal mode , than #303030 is fine

**Comment by bickman** [comment]
> https://drive.google.com/file/d/1--w0HqZR6XqOv6VcQnS5tLBga_6VO113/view?usp=drivesdk

Yes ,that is much better than dark blue background

**Comment by BAProductions** [comment]
There no light mode in my version of desk clock

**Comment by bickman** [comment]
> There no light mode in my version of desk clock

It is OK there is no light mode, I just don't recommand the background color which is toooooooo blue

**Comment by BAProductions** [comment]
It permanent dark mode like iOS

**Comment by bickman** [comment]
> It permanent dark mode like iOS

Cool , I haven't noticed that ios clock always have a dark backround.

**Comment by BAProductions** [comment]
> > There no light mode in my version of desk clock
> 
> It is OK there is no light mode, I just don't recommand the background color which is toooooooo blue

Maybe you submit mine commit to the lineage Gerrit & tag me Gerrit.

https://github.com/LightningFastRom/android_packages_apps_DeskClock/commit/330613ca70af3cd1161580c4e7d62a2b2f4aa172

https://github.com/LightningFastRom/android_packages_apps_DeskClock/commit/abd9674456b67e9b81f483ae715fb78830a86c39

https://github.com/LightningFastRom/android_packages_apps_DeskClock/commit/31b2491e4040b2ed04f657140ff3e0c9cdfb9fbb

https://github.com/LightningFastRom/android_packages_apps_DeskClock/commit/7ee3a4d559b05d9deea72405f130ac4c0d89d70c

**Comment by BAProductions** [comment]
> > It permanent dark mode like iOS
> 
> Cool , I haven't noticed that ios clock always has a dark backround.

Yea it does

**Comment by bickman** [comment]
> > > It permanent dark mode like iOS
> > 
> > 
> > Cool , I haven't noticed that ios clock always has a dark backround.
> 
> Yea it does

Because I always use dark mode in my iPhoneX which use OLED screen

**Comment by BAProductions** [comment]
> > > > It permanent dark mode like iOS
> > > 
> > > 
> > > Cool , I haven't noticed that ios clock always has a dark backround.
> > 
> > 
> > Yea it does
> 
> Because I always use dark mode in my iPhoneX which use OLED screen

Same

**Pull request closed without merging**
